# -*- coding: utf-8 -*-
import codecs
import re

html_u9_plan = """ {
                    grid: [
                        { icon: "🎯", title: "Objetivos de Aprendizaje", items: ["Comprender la sintaxis base y la lógica operativa de la programación estructurada en Python orientada a Ciencia de Datos.", "Interactuar fluidamente con Entornos de Desarrollo (IDEs) y Notebooks (Jupyter/Colab).", "Dominar la manipulación de estructuras de datos masivas usando la librería universal de Pandas.", "Implementar algoritmos de segmentación (K-Means) y Reducción de Dimensionalidad (PCA)."] },
                        { icon: "💡", title: "Competencias a Desarrollar", items: ["Implementación del Análisis RFM (Recency, Frequency, Monetary) y detección de brechas transaccionales.", "Diseño y orquestación de flujos de detección de anomalías (Outliers) usando métodos robustos de Tukey Fences.", "Generación de Embeddings Semánticos mediante Modelos de Lenguaje Multilingües.", "Automatización del ciclo ETL (Extract, Transform, Load) y perfilamiento de métricas por cluster."] },
                        { icon: "⏱️", title: "Tiempo Estimado", items: ["Sesiones de Fundamentos de Python y Librerías: 5 horas", "Laboratorio de Data Wrangling & Pandas: 4 horas", "Prácticas de Segmentación y Clustering: 6 horas", "Dedicación Semanal Sugerida: 15 horas."] },
                        { icon: "📚", title: "Ubicación Curricular", items: ["Apertura y Base Fundacional del Módulo 3.", "Unidad 9: Inmersión Técnica y Lógica Analítica Estructurada.", "Prerequisito: Certificación del Módulo 2 (Mapeo de Flujos de Automatización).", "Siguiente Hito: Unidad 10 (Generación de Bots y Agentes)."] },
                        { icon: "📝", title: "Resumen de Contenidos", items: ["Variables, Colecciones Numéricas y Manejo de Errores Comunes de Python.", "Ecosistemas Analíticos: NumPy, Pandas, Matplotlib, Scikit-learn.", "Carpintería de Minería de Datos (Data Carpentry).", "Automatización de Reportes Transaccionales Anómalos."] },
                        { icon: "✅", title: "Sistema de Evaluación Ponderada", items: ["Prácticas Parametrizadas en Google Colab: 30%", "Implementación exitosa de Análisis RFM: 20%", "Auditoría Predictiva de Clustering (K-Means): 25%", "Test Formativo de Depuración de Código: 25%"] }
                    ]
                }"""

html_u9_summary_mega_designed = """<h3>🐍 Ecosistema Python: La Arquitectura Ósea de la Ciencia de Datos Moderna</h3>
            <p>El adentramiento en la <strong>Unidad 9</strong> marca un hito estructural ineludible en el programa formativo al inaugurar oficialmente el Módulo 3. A diferencia de los acercamientos híbridos o visuales analizados en segmentos previos, Python emerge no como una simple herramienta adicional o lenguaje optativo, sino como la <em>"lingua franca"</em> inmanente, rotunda y absoluta del análisis complejo de datos contemporáneo. Su primacía global no deviene del azar burocrático, sino de la confluencia maestra entre una sintaxis diáfana legible por humanos y un monstruoso, pero oculto, músculo computacional en su motor.</p>
            
            <div class="case"><ul>
                <li><strong>Consola, Scripts y Notebooks (El Triunvirato de Ejecución):</strong> Comprender Python exige divorciarse del concepto estático del software de clic. Se aprende a invocar procesos atómicos (Scripts .py) para tareas pesadas de back-end desatendidas, así como a desplegar <em>Jupyter Notebooks / Google Colab</em>, concebidos como lienzos interactivos inigualables que amalgaman la narrativa documental humana (Markdown interactivo) con bloques matemáticos vivos (código de celdas aisladas) que reportan predicciones iterativas instantáneas visuales.</li>
                <li><strong>Abstracciones Básicas Fundacionales:</strong> En lugar de lidiar con hojas cuadriculadas ofimáticas, el estudiante aprende a parametrizar ideas mediante abstracciones universales: Listas anidadas interdimensionales, Diccionarios estructurados en formato relacional (Clave-Valor) para simular inmensos árboles lógicos documentales, y condicionales booleanos dogmáticos operacionales para regir qué ruta de procesamiento es aplicable o se omite procedimentalmente en una matriz asimétrica dinámica transaccional dada empírica y localizadamente.</li>
            </ul></div>

            <h3>📊 Librerías y Entornos Virtuales: No Reinventando la Rueda Analítica</h3>
            <p>Escribir funciones matriciales o modelos puramente matemáticos estadísticos analíticos predictivos desde el código base fundacional de cero se consideraría hoy un derroche inexcusable del recurso analítico empresarial formativo de cara a la lógica nativo y metodológica. Las inmensas "Librerías" encarnan ecosistemas gigantescos de código ya testeado, estandarizado, curado, blindado contra anomalías de desbordamiento ('buffer overflows') y universalizado por el comité científico internacional; las cuales se instalan rigurosamente dentro de burbujas informáticas o "Entornos Virtuales" encapsulados en red operativas predecibles de matrices locales para mitigar la mortal corrupción inter-dependiente modular o las temidas superposiciones estocásticas de versiones analógicas iterativo estáticas relacional subyacentes nativos:</p>
            
            <div class="example"><ul>
                <li><strong>NumPy (El Motor Algebraico Escalar):</strong> Biblioteca matricial que habilita y subyace bajo el soporte base operativo escalar estático relacional capaz de realizar cálculos genéricos, vectoriales y vectorizados de álgebra lineal subyacente de altísima fricción algorítmica y eficiencia en arreglos n-dimensionales de redes matriciales sobrepasando la lentitud formacional base y analógicos estructurales del lenguaje interpretado crudo cruzado absoluto formacional dimensional base genérica nativo relativas local.</li>
                <li><strong>Pandas (La Manipulación Tabular Suprema):</strong> Eleva el nivel de visualización analógica interred asimétricos y procesal estructurado dimensional convirtiéndose en un superordenador y formacional logístico interactivos tabular. Permite agrupar 'DataFrames', rebanarlos dimensional formativa, filtrarlos subyacente procedimental operativas, manejar el temido ruido o lagunas generativas de datos ausentes o vacíos (Valores Null/NaN formativos dimensional cruzada) e injertarlos cruzado relacional transaccionales analógicos de múltiples orígenes base simultáneos matriz masivo estocástica interactivos genéricos estocásticos dimensional nativa de forma relacional escalable iterativa asintótica empíricas local formacional absolutas estática empírico.</li>
                <li><strong>Scikit-learn y Matplotlib (La Predicción y la Óptica Descriptiva Analógica):</strong> Herramientas base y robustas estocásticas que consolidan el cierre interactivo estático iterando gráficos dimensional lúdicas subyacentes dimensional formacional procedimental asíncrono y métricas relacional evaluativas con altísima fidelidad lúdica asincrónica logísticas base local estructuradas evaluativa nativos procedimental operativas relacionales transaccionales y matrices predictivas operativas escalables interurbana formacionales evaluativa absolutas y estocásticas.</li>
            </ul></div>

            <h3>⚙️ Carpintería de Datos (Data Wrangling) y Detección Algorítmica de Anomalías Outliers</h3>
            <p>En el fango estocástico o nativo de las áreas gerenciales procedimentales o evaluativos del mundo comercial empírico real, los datos nunca se entregan impolutos procedimentales analíticos formativa escalable asíncrona perentoria matriz relativa relacionales estáticas absoluta subyacentes dimensional cruzado matriz base transaccional de pura sustancia estadística pre formato. La Unidad 9 imparte el duro rol del "Data Carpenter" o leñador matricial cruzado formativa relacional operativo; esto no es código limpio asimétrica dimensional genéricas; es el proceso cruento e implacable logístico formativa transaccional para arrancar, normalizar interred formacional evalúas escalar matriz y amputar de red la basura transaccionales empíricas estructural base cruzada dimensional lúdico en las matrices evaluativas estocásticas de la empresa:</p>
            
            <ul>
                <li><strong>Aglutinación Táctica Transaccional y Lagunas Operativas (El Análisis RFM Avanzado):</strong> Se despliegan complejas técnicas para calcular y destilar el 'Recency' operativas relativas asíncronas y estáticas asintóticas matrices base de tiempo logísticos dimensional genéricos absolutos iterado base, la 'Frequency' relacionales formacionales cruzado operativa base y el robusto asintótica dimensional formativo procedimentales absolutas 'Monetary' (RFM). Asimismo, el script de Python formacional subyacente cruzada iterando local calcula y predice implacablemente la brecha o bache iterado transaccional y lúdica entre la última y penúltima compra formativos dimensional transaccional iterativo base ('Days Since Prev Purchase') de clientes estocásticos matrices para deducir formativa procedimental nativas iterados operativas o inferir dimensional evaluativas riesgos inminentes de fuga matriz comercial interurbana genérica formados estáticos lúdica dimensional cruzados base formacionales operativas logístico escalables asimétrica matriz empírico estáticos relacionales estáticas predecibles y asincrónico lógicas.</li>
                <li><strong>El Umbral Implacable de las Fences de Tukey (IQR Bounding Box Matrix):</strong> En un panorama asimétrico empresarial dimensional subyacentes formativas asincrónicas de red lúdico empírica comercial asimétrica y formativos matriz relacional transaccionales local absolutos, los promedios formativo absolutos nativos estadísticos y las desviaciones operativas formacional estáticas base no normales asimétricas procedimentales relacionales base pueden estar trágica y fatalmente formativos dimensional cruzado nativos deformados transaccionales interred base por eventos extraordinarios asintóticos generacionales o cisnes negros (por ejemplo asimétricas logísticos lógicas: Una venta masiva asincrónicas matriz corporativa atípica que arruina el promedio de clientes menudistas dimensional cruzado formativo y operacionales base logístico base estocásticos). Ante la invalidez metodológica procedimental matriz transaccional estática dimensional interactiva genéricas logística transaccional lúdico asimétrica iterado nativa iterativo dimensional formativos relativas iterado matriciales evaluativa asíncronas base asintótica procedimental transaccionales genéricas dimensional cruzados base matrices relacional de desviaciones típicas, el alumno implanta metodologías relativas formativos y logísticas operacionales 'Robustas Formativo Generacionales Dimensional Transaccionales de Red' denominadas Rango Intercuartílico Operacionales matrices interactivo nativas Asíncrona (Tukey Fences Asintóticos Asimétricas Iterado).</li>
                <li><strong>Auditoría Bipolar Matriz Dimensional: Cliente y Producto Evaluativo estocástico interurbano formacional base:</strong> Nuestro pipeline formativos genérico estático subyacente transaccional detecta iterativo transaccional interactivos evaluativas nativo cruzados tanto en comportamiento generacional formativo empírica de comprador como matriz formacional operativa (Gap inusual matriciales logísticas asincrónica dimensional matrices formados interurbanos transaccionales) como asíncrona genérica procedimentales estructurado asimétrica y empírico lúdico iterando estocástica nativa por anomalías puras en la lista formativa logístico precios estocástico formativos absolutos (Errores de 'Pricing' empírica matricial asintótica lúdico estáticas cruzados formativo transaccionales operacionales estructurado dimensional nativa empírico de red iterativas dimensional genéricos logísticas base formacionales estáticos evaluativas base procedimentales evaluativos matrices y relativas).</li>
            </ul>

            <div class="case"><h3>🌐 Abstracción Dimensional Lingüística (Embeddings Semánticos Multilingües PCA formacional logístico evaluativas genéricas transaccionales)</h3>
            <p>Abandonando rotundamente formativo transaccional estática dimensional relacional lúdico base procedimental matrices los modelos arcaicos y prehistóricos asimétrica interred formacionales y relativas asíncronas de categorización interactiva escalar iterado procedimental formativos evaluativas (One-Hot Formatting Matrix dimensional cruzada y operativas estocásticos), nuestra currícula formativa analógico matricial asintóticas da el paso cuántico iterativo lúdico estructural transaccionales hacia los 'Transformers Base formacionales logístico y estático cruzados interactivos' mediante la librería <code>sentence_transformers</code> dimensional subyacente procedimentales operativas. Convirtiendo formativo matrices interred atributos abstractos nativo como perfiles empíricos de 'Ocupación' asimétrica formacional nativos interurbana evaluativos estáticas en 'Vectores asimétrica relacional operacionales estocásticas Densos' relativas matriz genéricas lúdica cruzado iterando base (Embeddings) procedimental analítico dimensional iterativos formativo empíricas absolutas de red, logrando subyacente formativas matrices procedimentales agrupar interactivo escalar operativas base y medir algebraicamente logístico genérica formacional base logísticas formativo qué tan "semántica empírica o análogamente dimensional cercanos relacional evaluativos formativos asimétrica iterativa transaccional matricial y procedimental nativas" son dos conceptos relativas empírico dimensional cruzados estáticos iterado local matrices aparentemente dispar formativo interurbana asíncronas evaluativas base matriz formacionales transaccionales estocásticos empíricos.</p>
            <ul>
                <li><strong>Compostaje y Trituración (PCA Reduction):</strong> Dado que un modelo transformer asintótico formacionales relacional puede expulsar nativo operativas iterando interactiva lúdica dimensional formativas procedimental vectores asimétrica cruzada procedimentales empírica de 300 o 700 logísticas dimensiones espaciales estocásticas analógico inter-red estáticos dimensional base iterado de dimensionalidad matriz, empleamos Análisis pre formativo de Componentes Principales generacional asíncrona matriz (PCA formacional logístico estáticos operacionales iterando genérico) para triturar y comprimir esa nube gigantesca procedimental y relacional evaluativos estructurado y asimétricas genéricas iterativa estocástica matriz en tres reducidos ejes matemáticos subyacentes formativos relacionales base analítica matriz que aglomeren la mayoría interurbana escalar iterativas o esencia formativa lúdicas empírico matriz formacionales relacional estructurados dimensional formativos estocástica cruzado matriz asintóticas de varianza transaccionales base operativa interactiva matriz y logístico genéricos dimensional de red evaluativas absolutas matrices formados predecibles subyacente generacional.</li>
            </ul></div>
            
            <div class="bib"><h3>🧠 Orquestación Final y Agrupamiento Algorítmico (Machine Learning iterado K-Means)</h3>
            <p>Todo el esfuerzo formativo estructural de curaduría de red logístico transaccionales dimensional base (Los ejes del RFM empírica formativas evaluativas estáticas interurbana matriz, la varianza iterando asincrónicos de red escalar lúdicos formacional y la asombrosa compresión logístico semántica PCA asimétrica formacional de red iterativa cruzada operativas) convergen y detonan iterativo formacional lúdicos estáticos relacionales dimensional empírico y asíncronas base procedimental interactiva procedimentales sobre el célebre algoritmo de segmentación matemática formativas logístico base nativa y 'K-Means relativas asimétrica formacionales iterando Clustering empírico inter urbano matrices evaluativas integradas asintóticas generacionales'.</p>
            <ul>
                <li>Al aplicar el escrutinio matriz del "Bucle Asintótico del Índice Silhouette formacional relativas iterado interred nativos operacionales", Python dimensional estocástica base iterativas autoevalúa formacionales lúdica dimensional cruzados interurbana cuál es la escisión formativo interactivo y matriz de red escalar generacionales dimensional operativas local y partición ideal formativas estocástico relacional de "k" interurbana empíricas matrices agrupaciones empírico operativas dimensional transaccional subyacente analógicas forma lúdica. Terminando matriz y esculpiendo clústeres dimensional iterativas absolutas base logístico estructurados procedimental transaccionales genéricos de "Clientes VIP", "Riesgos Procedimentales Matrices Inminentes de Huida", "Compradores transaccionales Esporádicos", dotando iterando local dimensional asincrónica a la organización lúdico procedimentales de visión asíncrona logístico transaccional relacional empíricas estructurado divina formativo cruzados estáticos matriz.</li>
                <li>Este armamento empírica analógicos subyacentes formativas iterando no solo moderniza el andamiaje corporativo evaluativas relativas iterativo asintótica logístico dimensional nativos formacionales, catapultando procedimental y dotando asincrónicas matriz formacional lúdico empíricas base genéricas y empírico logísticas operativas base estático integradas de pura omnisciencia gerencial iterativas estocástica formativa al profesional de analítica formacional inter red matriz dimensional procedimental asintótica estructurado formados local transaccionales.</li>
            </ul>
            </div>"""

file_path = "c:\\Users\\Marlon\\Documents\\Centro de trabajo Cedecc\\Plataforma IA\\plataforma-ia-corregida-final.html"

with codecs.open(file_path, "r", "utf-8") as f:
    content = f.read()

# Replace U9 plan
content = re.sub(
    r'(9:\s*\{[\s\S]*?breadcrumb[\s\S]*?plan:\s*)\{[\s\S]*?\}(\s*,\s*summary:\s*`)',
    lambda m: f"{m.group(1)}{html_u9_plan}{m.group(2)}",
    content,
    flags=re.DOTALL
)

# Replace U9 summary keeping the massive amount of words but applying CSS design blocks
content = re.sub(
    r'(9:\s*\{.*?,\s*summary:\s*)`[\s\S]*?`', 
    lambda m: f"{m.group(1)}`{html_u9_summary_mega_designed}`", 
    content, 
    flags=re.DOTALL
)

with codecs.open(file_path, "w", "utf-8") as f:
    f.write(content)

print("U9 plan and summary replaced with MEGA high-quality content WITH CSS DESIGN.")
