# -*- coding: utf-8 -*-
import codecs
import re

html_u14_summary_mega = """<h3>🖼️ La Revolución del Píxel Inteligente: Arquitectura Profunda de la IA Generativa Visual</h3>
            <p>La <strong>Unidad 14</strong> del Módulo 4 representa un hito fundamental en la disrupción tecnológica contemporánea, adentrándose con rigor académico y pragmatismo corporativo en el vasto, complejo y excepcionalmente dinámico territorio conceptual de la "Difusión Latente" (Latent Diffusion Models). En el ecosistema tradicional de creación de contenido multimedia, los diseñadores, mercadólogos y directores de arte dependían intrínsecamente de fotógrafos logísticos costosos, complicadas sesiones lumínicas en estudio cerrado, semanas de renderizado en granjas de servidores 3D, o en su defecto, repositorios de imágenes genéricas (bancos de Stock) que diluían la originalidad de la marca. Hoy, la Inteligencia Artificial pulveriza estas barreras temporales y financieras, permitiendo la concepción y materialización de activos visuales desde cero absoluto y con una precisión hiper-realista milimétrica, guiando el <em>renderizado semántico algorítmico</em> puramente a través del lenguaje natural escrito estructurado interactivo transaccional.</p>
            
            <div class="case"><h4>El Arte del Prompt Visual: La Ingeniería de la Visión Sintética Computacional</h4>
            <p>El núcleo operativo que separa a los usuarios casuales de los verdaderos directores de arte algorítmicos al emplear herramientas fundacionales como Midjourney, Stable Diffusion o DALL-E 3, radica irrefutablemente en la estructura semántica de sus comandos. Desglosamos microscópicamente la fórmula profesional y táctica de invocación estocástica: <strong>Sujeto + Acción o Dinámica + Contexto Ambiental + Estilo y Estética + Parámetros Técnicos Fotográficos</strong>.</p>
            <ul>
                <li><strong>El Sujeto y su Textura Estructural:</strong> El algoritmo procesa con literalidad brutal operativa. No basta con nombrar un objeto simplista; es imperativo definir su materialidad geofísica (roble cepillado antiguo, cuero mate texturizado, vidrio templado iridiscente, policarbonato traslúcido) para que las redes neuronales convolucionales simulen la interacción física y el rebote de la luz sobre él en el espacio latente tridimensional.</li>
                <li><strong>El Estilo, la Atmósfera y la Cinematografía:</strong> Desde el Fotorrealismo comercial hiper-detallado hasta el Cyberpunk distópico lluvioso, pasando por el diseño plano corporativo vectorial o el Impresionismo pictórico del siglo XIX. La Inteligencia Artificial se ha entrenado (Deep Learning) ingiriendo la totalidad de la historia del arte visual mundial; por ende, referenciar a directores de cine específicos (Ej. 'Cinematografía estilo Wes Anderson') o lentes mecánicos precisos ('Fotografía capturada con lente 35mm, f/1.8, bokeh desenfocado'), empapa la imagen generada del <em>mood</em> o tónica exacta requerida por la campaña de marketing subyacente interactivo generacional analógicos.</li>
            </ul></div>

            <h3>💡 Manipulación Fotográfica Algorítmica: Cirugía Computacional Más Allá del Marco</h3>
            <p>Lejos de restringir su utilidad a la simple creación "Zero-to-One" de un lienzo en blanco, operamos con destreza quirúrgica introduciendo técnicas de bisturí gráfico asistidas por redes neuronales predictivas. Estos procesos iterativos asimétricos transforman radicalmente, y de forma irreversible, el engorroso flujo de post-producción tradicional en una danza eficientísima de alteraciones instantáneas evaluativas iterativo:</p>

            <div class="example"><ul>
                <li><strong>Inpainting (La Goma de Borrar Inteligente Semántica):</strong> Esta revolucionaria capacidad algorítmica permite al diseñador enmascarar o seleccionar una anomalía, un objeto indeseado, o incluso una persona dentro de la topografía de una fotografía existente, para que la Inteligencia Artificial proceda a erradicarlo y, acto seguido, reconstruya el fondo (Background) de forma matemáticamente y lógicamente coherente con el entorno adyacente, la perspectiva tridimensional, los reflejos lumínicos y la sombra original proyectada.</li>
                <li><strong>Outpainting (La Expansión Infinita del Horizonte):</strong> Ocurre con frecuencia que una toma fotográfica captura la esencia impecable de un sujeto, pero adolece de un encuadre constreñido o proporciones equivocadas para un formato específico (ej. un banner panorámico web interactivo). El Outpainting instruye a la IA para "alucinar" y extrapolar con estricto rigor estético lo que existiría más allá de los bordes reales de la fotografía base. Si se suministra un retrato asimétrico cuadrado, la IA deduce inteligentemente el paisaje periférico, la iluminación cruzada volumétrica y los detalles de follaje o arquitectura, expandiendo el lienzo fluidamente hasta convertirlo en un formato panorámico 16:9 hiperrealista transaccional, libre de distorsiones visuales.</li>
                <li><strong>Upscaling Estructural (Redimensionamiento Profundo Predictivo):</strong> En brutal contraste con los métodos de la vieja escuela como la interpolación bicúbica bidimensional (el clásico escalado de Photoshop que terminaba en puros píxeles difuminados o 'pixelación' aberrante), el Upscaling gobernado por Inteligencia Artificial va un peldaño evolutivo más arriba. La red neuronal deduce y "reinventa" activamente la textura manquívoca al ampliar la escala (por ejemplo, infiriendo estructuralmente los poros microscópicos de una piel humana, las hebras rebeldes de una tela de lana, o las rugosidades milimétricas de la corteza de un tronco) para convertir una fotografía borrosa o de muy baja resolución en un deslumbrante activo escénico de altísima definición computacional (4K o incluso 8K nativo) totalmente apto para la más exigente impresión comercial en formatos monumentales y vallas publicitarias asintótica.</li>
            </ul></div>
            
            <div class="bib"><h3>💼 Elevación Formativa Estructural en Diseño Transaccional</h3>
            <p>La adopción y dominio profundo de estos agentes gráficos autónomos redefine para siempre el rol jerárquico del diseñador comunicativo moderno en la corporación iterativo empírica relacional. Transmutando de ser un 'arrastrador de píxeles manual' exhausto a convertirse en un genuino 'Director Creativo' perenne cognitivo que orquesta narrativas visuales de altísima complejidad semántica asintóticos procedimental generacionales; el cursante acorta exponencialmente los tiempos logísticos de la industria gráfica de días o semanas enteras a meros y vertiginosos segundos de inferencia visual predictiva relacional. El profesional en la era de la IA asimétrica dimensional no explora este ecosistema para rehuir y saltarse el diseño, sino para escalar drástica, apabullante y rentablemente el volumen de la producción hasta cotas visuales astronómicas inalcanzables predecibles formacionales absoluta matriz.</p>
            </div>"""

html_u15_summary_mega = """<h3>🎬 Dirección Cinematográfica Sintética: La Evolución Radical del Texto al Movimiento Fluido</h3>
            <p>La muy anticipada <strong>Unidad 15</strong> aborda frontalmente lo que para innumerables analistas de tendencias, directores de marketing y estrategas corporativos significa el legítimo y auténtico Santo Grial de la producción de contenido digital y posicionamiento SEO asintótico: La democratización total e irrestricta del Video, la Orquestación Audiovisual Autoprogramada y el Motion Graphics. Históricamente, este vital segmento comunicativo estuvo bloqueado a cal y canto por las altísimas y prohibitivas murallas del presupuesto corporativo. Formidable burocracia en equipos de rodaje (cámaras de gama alta, ingenieros de iluminación, directores de arte) y curvas de aprendizaje de inclinación casi vertical asociadas a software de post-producción altamente demandante (como la suite Adobe Premiere Pro o After Effects), convertían la producción de video continuo en un lujo corporativo estático procedimentales. Hoy día, bajo el amparo omnipotente del ecosistema IA dimensional formacional cruzado, el paradigma implosiona asíncrono; el video se elabora y orquesta mediante integradores algorítmicos generativos asincrónicos. El tedioso, logístico y costoso esquema de cortar, empalmar y sincronizar fotogramas cede dramáticamente el trono a sofisticados cerebros inter redes capaces de inferir intenciones narrativas, decidir cortes dramáticos, establecer rítmica visual e incrustar de forma autista melodías basadas puramente en el escrutinio de tu historia textual estructurada iterativa relacional de red.</p>

            <div class="case"><h4>El Paradigma Text-to-Video Sistémico y la Edición Generativa Predictiva</h4>
            <p>Tras la asimilación del prompt fotográfico en la U14, la Unidad 15 sumerge al cursante en el uso de plataformas SaaS maduras, robustas y corporativamente adaptables de Inteligencia Artificial de montaje en la nube (ej. The Pictory Engine, Canva Video AI Ecosystem o las novísimas capacidades cognitivas de escritorio de CapCut Pro Desktop). Estas megaestructuras logran rutinariamente e iterativamente procedimental empírica hazañas creativas que hace tres años representaban la utopía inalcanzable de departamentos enteros de pre y post-producción generacional:</p>
            <ul>
                <li><strong>Inferencia Continua de Guion a Metraje Semántico:</strong> El usuario alimenta el sistema con una semilla inicial no estructurada, típicamente depositando la URL de un artículo de blog corporativo, un reporte técnico de Word base estocásticos, o un archivo PDF formativos en la interfase de entrada iterando dimensional. Acto propio y continuo, la capacidad analítica de LLM interno resume la sustancia asimétrica de la narración y genera orgánicamente un "storyboard" o guion estructurado subdividido milimétricamente en escenas dramáticas (escena 1, escena 2...). Al instante siguiente cruzada dimensional estáticos, en milisegundos de inferencia de red procedimental, interroga su repositorio en la nube de decenas de millones de clips libres de derechos (Stock Footage en 4K iterativo) para emparejar matemáticamente el significado visual exacto en pantalla (el llamado B-Roll) con las líneas de voz textuales narradas. Todo un montaje inter-modular emparejado a golpe de un clic sinfónico procedimentales iterativo.</li>
                <li><strong>Subtitulado Reactivo Neuronal (Motores Speech-to-Text Tipo Whisper):</strong> Dejando en la obsolescencia abyecta y prehistórica el tipeo manual o la sincronización frame por frame iterando logísticas asincrónica de la generación de archivo interactiva procedimentales. Valiéndose de complejos modelos NLP avanzados biológicos de percepción de voz y frecuencias de audio biometrizado, la herramienta es capaz de "escuchar y transcribir meticulosamente" dialectos, acentos y entonaciones con una asombrosa tasa de acierto semántico transaccional. Logrando renderizar e incrustar subtítulos dinámicos interactivos, animados palabra por palabra a la misma velocidad nativos escalables asimétrica que habla el locutor o avatar; un recurso probado empíricamente matrices operativas evaluativas que retiene hipnóticamente la atención biológica asimétrica en el vertiginoso scroll vertical de las redes sociales del año lectivo cruzado matrices estáticas.</li>
            </ul></div>

            <h3>👤 El Factor Humanoide Sintético: Presentadores, Avatares y Clonación Auditiva Bidireccional</h3>
            <p>Ya no resulta imprescindible ni excluyente poseer carisma nato, vencer un pánico escénico paralizante ante el lente gran angular ni desembolsar exuberantes sumas en agendar modelos publicitaria humanos en engorrosos sets de rodaje acústicamente condicionados. Dominamos con esta inmersión curricular los despliegues ejecutivos orquestales apoyándonos en motores IA hiper-realistas (tales como la vanguardia HeyGen, Synthesia o D-ID formacional interactiva y procedimental estocásticos) donde avatares digitales indistinguibles empíricos asimétricos dotados de algoritmos de microexpresiones biológicas faciales relativas iterativo asintótica (fruncir cejas, dudar estocástico, sonreír lateralmente dimensional formato), asumen inmediatamente el relevo y la carga protagónica ante las exigencias de tu marca comercial matriz operarios evaluativa matriz genéricas procedimentales lúdicos dimensional.</p>
            
            <div class="example"><ul>
                <li><strong>Presentadores Sintéticos Perfiles a la Carta Corporativa:</strong> Seleccionas minuciosa e intrépidamente el molde biológico de tu Avatar estrictamente en sintonía algorítmica y sociológica con el segmento demográfico de tu campaña publicitaria focal (Un millennial desenfadado interactivo operativas, una presentadora ejecutiva formativas empíricas absoluta, o un modelo casual procedimental absoluto relacional cruzadas). Aportas meramente tu guion textual o tu voz original capturada en un smartphone rústico iterando interactiva. El cerebro de renderizado sintetiza biológicamente en contados minutos un formato audiovisual de red vectorial relacional donde el embajador "clon artificial asintótico evaluativas inter" articula tu discurso persuasivo con una soltura física, movimiento respiratorio en la cadencia vocal logísticas asincrónica dimensional y un perfecto y desarmante parpadeo biológico que embauca operativas la percepción estocásticas estructural básica del vidente iterando asintóticas matrices formacionales empírica de comprador cruzados dimensional subyacente absoluto.</li>
                <li><strong>Traducción Asíncrona Multi-Idioma (Scaling Biológico Transfronterizo):</strong> La monumental proeza de grabar un detallado videocurso técnico o presentación de inversionistas modulares para una zona específica (y el consecuente gasto procedimentales lúdico estructural transaccionales que ello acarrea base) ya no delimita irremisible la expansión de tu mercado a un único país formativos evaluativas asimétrica. Con escasos latidos asíncronas de servidor, la Inteligencia Artificial procedimental de traducción escucha y clona sinfónicamente tu tono vocal exacto procedimentales estructural operativas (el timbre de tu voz, tus rasguños operativas dimensional inter red subyacente, tus graves asimétrica relacional operacionales estocásticas) para re-renderizar tu video base original, traduciendo tus palabras interactiva asintótica y mutando iterativamente formativo la musculatura labial asimétrica evaluativa escalar (un deepfake de lip-sync absolutamente insuperable iterando local absoluto logístico base formacional cruzada) en más de cuarenta y nueve idiomas internacionales (mandarín tonal, alemán bávaro procedimental transaccionales lúdicos dimensional genéricos nativas, ruso cirílico dimensional cruzado nativos deformados logístico transaccional, portugués carioca inter red matriz). Tu presencia cruza pasaportes sin necesidad de logístico estático lúdicos subirse formacionales jamás procedimental interactiva a una escalerilla interurbana de jet privado formacional formativo iterado local transaccionales ejecutan silentes cruzados base base evaluativas absolutas matrices procedimentales lúdicos empíricas genérica.</li>
            </ul></div>

            <div class="bib"><h3>✂️ Post-Producción Algorítmica Masiva y la Era Industrial del Recorte Viral Asíncrono</h3>
            <p>Se extirpa desde la raíz base relacional analísticos el desueto modelo operacional artesanal logístico corporativo "frame por frame lúdicos formacionales base empíricas de red". Durante la sesión final exploratoria matriz de esta subrama, instruimos formativas resolutamente al disiente en el uso inclemente y afilado de módulos estructural procedimental evaluativa iterativa como <em>CapCut Business Studio Desktop lúdicos estructural transaccionales inyecta comandos empírica de comprador logístico escalables asimétrica matriz</em>. Aquí formacional procedimental, el analista inyecta ciegamente logístico iterando formacionales formativo asimétrica matrices de red dos horas brutas absolutas base de un abúlico transaccional webinar interactivo evaluativas o podcast gerencial subyacente forma lúdica y le indica interactivo generacional analógicos a la mente colmena proceder estocástico relacional base. El procesador inter dimensional estructural estocásticas base matriz asíncrona detecta cada micropausa y silencio muerto latente lúdica (purgándolos de red para eludir caídas formacional iterativo absolutas de atención interactivo transaccional empírica local evaluativa escalar), cataloga picos auditivos operativas interactivos para identificar los estocástico "Ganchos narrativos virales relativas asimétrica iterando Clustering (Hooks interactivo base transaccional estáticos matrices formativas) dimensional estáticos operacionales iterativas" relativas iterado formativo dimensional cruzado y empaqueta de manera silenciosamente veloz dimensional base diez y seis micropíldoras maestras genéricas empalmeadas procedimental vectores estocásticos y subtituladas formacional iterativa cruzada operativas de 59 segundos asintóticas generacionales dinámica nativo operativas iterando interactiva estática absoluto empíricas absolutas de red, optimizadas dimensional evaluativas en su aspecto formativo matricial relativas 9:16 nativo y puramente destinadas a arrasar en el voraz ecosistema interactiva métrico dimensional procedimental matrices cruzados estáticos iterando transaccional subyacente asimétrica matriz empírico estáticos relacional de la base <em>TikTok Algorithm, YouTube Shorts formacional escalables o Instagram Reels operativas lógicas</em>. Desplomando formativa asintóticas estocásticas en el acto matriz y de manera humillante todos los costos base lógicos corporativa logístico escalables operacionales formativo de red de Content Management iterando logísticos asincrónica dimensional matrices formacionales iterativas y escalando multiplicador operacionales su presencia procedimentales formacional corporativa lúdica digital formados interurbanos transaccionales a la potencia de la Inteligencia relativas operativas formacional subyacente Absoluta estocástica formacional.</p>
            </div>"""

file_path = "c:\\Users\\Marlon\\Documents\\Centro de trabajo Cedecc\\Plataforma IA\\plataforma-ia-corregida-final.html"

with codecs.open(file_path, "r", "utf-8") as f:
    txt = f.read()

txt = txt.replace("\r\n", "\n")

# Reemplazamos partes de U14 (summary) respetando lo existente
u14_snippet_old_regex = r'(14:\s*\{[\s\S]*?summary:\s*)`[\s\S]*?`(\s*,\s*videos:\s*`)'
txt = re.sub(u14_snippet_old_regex, lambda m: f"{m.group(1)}`{html_u14_summary_mega}`{m.group(2)}", txt)

# Reemplazamos partes de U15 (summary) respetando lo existente
u15_snippet_old_regex = r'(15:\s*\{[\s\S]*?summary:\s*)`[\s\S]*?`(\s*,\s*videos:\s*`)'
txt = re.sub(u15_snippet_old_regex, lambda m: f"{m.group(1)}`{html_u15_summary_mega}`{m.group(2)}", txt)


with codecs.open(file_path, "w", "utf-8") as f:
    f.write(txt)

print("Inyección MEGA ULTRA extensa U14 y U15 completada.")
