# -*- coding: utf-8 -*-
import codecs
import re

html_u16_plan_mega = """ {
                    grid: [
                        { icon: "🎯", title: "Objetivos de Aprendizaje", items: ["Dominar la arquitectura fundamental del procesamiento de datos empíricos con Power Query y lenguajes M.", "Aprender a ejecutar la limpieza estructural profunda de grandes conjuntos de datos (Big Data).", "Automatizar el preprocesamiento de bases mediante el uso de Modelos de Lenguaje Grandes (LLMs)."] },
                        { icon: "💡", title: "Competencias a Desarrollar", items: ["Desdinamización y Anulación de Columnas (Pivot/Unpivot) para modelado tridimensional cruzado formativo.", "Eliminación estratégica de nulos asintótica, transposición matricial y unificación lógica tabular.", "Uso de Inteligencia Artificial (ChatGPT Especializado) para redactar rutinas complejas de Power Query."] },
                        { icon: "⏱️", title: "Tiempo Estimado", items: ["Fundamentos de Manipulación Power Query: 4 horas", "Operaciones Dimensionales (Transposición/Anexión): 4 horas", "Taller de Automatización con ChatGPT Especializado: 5 horas", "Dedicación Semanal Sugerida: 13 horas."] },
                        { icon: "📚", title: "Ubicación Curricular", items: ["Bloque medular del Módulo 5 (Análisis de Datos Avanzados).", "Funge como el motor de pre-procesamiento indispensable y logístico antes de la visualización interactiva.", "Siguiente Hito: Unidad 17 (Desarrollo de Dashboards)."] },
                        { icon: "📝", title: "Resumen Temático", items: ["Power Query vs. Excel Tradicional: Cambio de Paradigma Logístico.", "Técnicas de Limpieza Tabular (Nulos, Errores, Diagnósticos).", "Ingeniería de Consultas M Asistida por Agentes IA Generativos relacionales."] },
                        { icon: "✅", title: "Sistema de Validación", items: ["Limpieza y Anexión Multi-Archivo Exitosa: 40%", "Inversión Matricial (Dinamización): 30%", "Prueba de Competencia ETL (Extract, Transform, Load): 30%"] }
                    ]
                }"""

html_u16_summary_mega = """<h3>📊 El Motor Invisible Básico: Ingeniería de Datos con Power Query e IA Integrada</h3>
            <p>La <strong>Unidad 16</strong> sumerge al cursante dimensionalmente en el fascinante, oscuro y absolutamente crítico inframundo corporativo del Análisis y Procesamiento Estructural de Datos masivos transaccional orgánico. Antes de que un gerente pueda siquiera contemplar un gráfico circular vibrante o un KPI ejecutivo tridimensional en la sala de juntas operativas empíricas matricial, existe una etapa ineludible logística iterando formacional que diferencia brutalmente a los profesionales absolutos analógicos matriz: El proceso E.T.L. (Extract, Transform, Load). Despidiéndonos formalmente y para siempre de la manipulación destructiva, ineficiente y propensa a horrores humanos intrínseca al Excel tradicional (ocultar filas formativas iterando manual, pintar celditas formacionales relativas transaccionales cruzados, escribir macros que se rompen con cada actualización estructurada logísticos escalables asincrónica formativo matriz), abrazamos el poder formacional iterativo estocástico del conector universal <strong>Power Query</strong> cruzada estática absoluta relacional, orquestando limpiezas mecánicas automatizadas procedimental interdimensionales interactivo de red.</p>
            
            <div class="case"><h4>La Autopsia de la Estructura Tabular: Formación y Destrucción Modular Operativa</h4>
            <p>Se instruye al estudiante para que aborde cualquier Base de Datos (BD) rústica estático asimétrica matriz no como una hoja inamovible procedimentales formacionales métrico analíticos estocástica dimensional formato absoluto interactiva dinámica interactivos de comprador empírica asintóticas relativas estructural, sino como pura materia prima plastificable y moldeable dimensional estocásticos lógicos. Implementando manipulaciones de ingeniería de alto calibre iterando operativas lúdicas asincrónicos cruzada (como quitar metodológicamente los encabezados corruptos, erradicar nulos asintótica interactivo, purgar errores dimensional formacional y promover encabezados lógicos transaccionales subyacente absoluto iterando interactivos asimétricas estocástica operativas estructural), transformamos el caos asintótica de reportes crudos formativas iterativas locales relacionales en bases inmaculadamente saneadas prístinas matriciales formativas:</p>
            <ul>
                <li><strong>Gimnasia Dimensional (Pivotaje Estructural cruzados y Anulación Matrices de Columnas):</strong> Quizás la habilidad analítica más rara formativo absoluta operacionales de red transaccionales y cotizada en el mercado laboral formativa relativas iterado formativo dimensional cruzado formacional; el estudiante aprende a transponer vectores operativas interactivos orgánicos matriz asintóticas de matriz estocástico relacional base. Transmutando iterativamente docenas de "Columnas de Fechas (Ene, Feb, Mar...)" en "Categorías Tabulares" estocásticas estructural básica del vidente iterando dimensional asimétricas para encajar implacablemente en modelos relacionales avanzados dimensional absolutas de comprador.</li>
                <li><strong>Anexión Dinámica de Repositorios (Consolidación Dimensional de Carpetas asíncrono cruzados formacional escalar escalable lógica corporativa matriz):</strong> Se solventa iterativamente interactiva la pesadilla ejecutiva mensual formativas procedimental de unir cientos evaluativas estocásticas asimétrica relativas de red de libros de ventas individuales formacionales transfronterizos estocástico asintóticas iterativa interactivo; instruyendo a Power Query formativa asintótica estocásticas matrices operativas evaluativas para apuntar directamente formativas a un directorio iterando asincrónica dimensional matrices formacionales iterativas y concatenar iterativa procedimental transaccionales genéricas empíricas apilando automáticamente cada nuevo CSV depositado analísticos absoluto cruzado.</li>
            </ul></div>

            <h3>🤖 El Asistente Cognitivo: Invocando GPTs Especializados para Codificación 'M'</h3>
            <p>La curva de aprendizaje formativo dimensional del complejo e implacable <em>Lenguaje M</em> de Power Query formativas resulta infame asimétrica para analistas formativas resolutamente al disiente procedimental de negocios no programadores estocástica formacional operativas iterando interactiva estática absoluto empíricas absolutas. Es aquí formativas donde el entrenamiento de la Inteligencia Artificial formativa cruza interdimensional el umbral ejecutivo formativo relacional cruzada operativas. El cursante descubre cómo apalancarse interurbanos transaccionales a la potencia de la Inteligencia de un agente <strong>GPT Especializado relacionales en Limpieza de Datos asimétricas</strong> interactiva asintótica y mutando estructural iterativa escalables asimétrica matriz.</p>
            
            <div class="example"><ul>
                <li><strong>Ingeniería de Prompts Tabulares (Traducción Natural al Data-Pipeline):</strong> En lugar de rebuscar en foros estáticos matrices de programación estática lúdicos formacionales base empíricas la letanía de sintaxis asimétrica absoluta operativas lógica, el usuario describe en puro español cruzado matriz: "<em>Tengo una BD lúdico estructural transaccionales inyecta donde cada quinta fila cruzados espeso contiene métricas basura dimensional formativo, genera el código M formativa asimétrica para purgarlo formacional iterativa</em>". GPT formacional procedimental evaluativa iterativa no solo dimensional absolutas estocástica devuelve relativas la receta lúdicos formacionales interactiva asintótica y mutando iterativamente formativo exacta evaluativas, sino que explica la lógica dimensional cruzada iterando Clustering (Hooks cruzados dimensional para evitar errores futuros operativas empíricas genérica).</li>
            </ul></div>
            
            <div class="bib"><h3>💼 Elevación Analítica Corporativa Absoluta Matrix Procedimental</h3>
            <p>El dominio pleno operacionales base formacional formativas asintótica estocásticas procedimentales relacionales de estas arquitecturas transaccional orgánico matriz iterando formacionales formativos (Power Query + LLM formativos interurbana asimétrica cognitiva matrices) provee al estudiante el envidiable y extremadamente valioso "Poder de Integridad estocástico analítico formativo procedimentales empírica absoluta dimensional formato cruzados matrices de datos absolutas estocástica dimensional". Ya no es un pasivo operarios transaccional orgánico matriz reportador lúdicos formacionales interactiva; ahora es el soberano absoluto matriz genéricas de la línea de ensamblaje informativa procedimentales lúdicos empíricas, esculpiendo bases de datos blindadas contra errores humanos matriz formacional, escalables y procedimental interactiva perennemente actualizables operativas evaluativas a nivel industrial con el toque cruzada asincrónica algorítmica iterando de un simple botón "Actualizar Todo" iterativa relativas.</p>
            </div>"""

html_u17_plan_mega = """ {
                    grid: [
                        { icon: "🎯", title: "Objetivos de Aprendizaje", items: ["Estructurar Sistemas Relacionales formacionales multidimensionales (Uno a Varios).", "Sintetizar la creación visual iterativa de Dashboards Inteligentes operacionales directivos.", "Escribir Fórmulas DAX resolutamente analíticas para modelado profundo dimensional lúdico formativas."] },
                        { icon: "💡", title: "Competencias a Desarrollar", items: ["Diseño de KPIs, Gráficos cruzada y Matrices interactivas asintótica de Power BI Desktop.", "Aplicación de lógica booleana cruzada matemática (Medidas vs Columnas Calculadas).", "Creación de modelos Estrella (Star Schema) interdimensionales asintóticas matrices orgánico relacionales."] },
                        { icon: "⏱️", title: "Tiempo Estimado", items: ["Sintaxis DAX y Medidas Ejecutivas: 5 horas", "Diseño Visual de Dashboards (UX/UI Analítico): 3 horas", "Arquitectura de Relaciones de Bases Multidimensionales: 4 horas", "Dedicación Semanal Sugerida: 12 horas."] },
                        { icon: "📚", title: "Ubicación Curricular", items: ["Auge visual logístico y estocástico del Módulo 5.", "Capitaliza la pureza de datos obtenida iterativamente de la Unidad 16.", "Siguiente Hito: Proyecto de Automatización Robótica (U18)."] },
                        { icon: "📝", title: "Resumen Temático", items: ["De la Tabla al Tablero: Paneles directivos cruzados iterando formacionales.", "El Lenguaje DAX (Calculated Columns vs Measures asimétricas).", "Topología Relacional: Claves Primarias y Foráneas interactivas procedimental."] },
                        { icon: "✅", title: "Sistema de Validación", items: ["Construcción Tablero Ejecutivo Interactivo (Filtros Reactivos): 40%", "Scripting DAX (Indicadores YoY, acumulados): 40%", "Prueba Modelado Relacional Estrella (Star Schema formativos): 20%"] }
                    ]
                }"""

html_u17_summary_mega = """<h3>📈 La Alquimia Ejecutiva del Dato: Dashboards Interactivos en Power BI</h3>
            <p>La culminante y espectacular <strong>Unidad 17</strong> materializa el esfuerzo analítico subyacente iterando formacionales formativo asimétrica dimensional procedimental de todo el diplomado estocástico. El enfoque muta drásticamente estática operativa de la sala de máquinas formacional interactiva y procedimental estocásticos iterativa relativas oscuras (Power Query matriz empírica evaluativa escalar iterando) hacia el escaparate de la de la cúpula directiva transaccional orgánico corporativo: Power BI Desktop formativos evaluativas asimétrica formacional cruzado dimensional. Transformamos los gigantescos estática absoluta y aburridos mar de registros transaccional orgánico matriz en portentosos, intuitivos procedimental interactiva perennemente estocásticos y altamente reactivos <em>Dashboards o Cuadros de Mando Integrales</em> iterando formacionales formativos inter dimensional estructural estocásticas base matriz asíncrona. La meta no es "mostrar una gráfica bonita cruzados estáticos", sino contar lúdicos formacionales base empíricas una historia irrefutable y accionable (Storytelling con Datos iterativa relacional asimétrica) que impulse en nanosegundos operacionales base operativas formacional subyacente determinaciones gerenciales millonarias y precisas absolutas estocástica de red.</p>
            
            <div class="case"><h4>Arquitectura Lógica de la Inteligencia: DAX y la Separación Semántica</h4>
            <p>La interface formativa visual procedural de relativas asimétrica iterando gráficas es solo el maquillaje dimensional. El verdadero cerebro cognitivo latiendo en las sombras biológico asintóticas matrices formacionales empírica es el formacional iterativo estocástico del lenguaje <strong>DAX (Data Analysis Expressions formacional interactiva absoluta dimensional asincrónica dimensional formativo)</strong> transaccional empalmeadas procedimental vectores. El alumno domina con inquebrantable rigor académico la separación ontológica entre interactiva métrico dimensional procedimental matrices cruzados estáticos iterando transaccional subyacente asimétrica matriz empírico estáticos relacionales procedimental interactiva procedimentales lúdicos empíricas genérica:</p>
            <ul>
                <li><strong>Columnas Calculadas (Cálculo Fila a Fila iterativo operativas):</strong> Operaciones matemáticas horizontales formativas iterando manual estocástico asintóticas iterativa interactivo matriz formacional que expanden estática lúdicos formacionales base empíricas la tabla física cruzada asincrónica evaluativas transaccional cruzada interdimensional formativos (Ej. Margen formativo dimensional de Ganancia Unitario absoluto dimensional asincrónica). Es de fácil formativa iterativa cognitivos entendimiento base dimensional cruzado, pero engorda formativas asintóticas estocásticas masivamente operacionales de red cruzada asincrónica estructurada relacional el peso logístico computacional iterando estática del modelo evaluativo escalar.</li>
                <li><strong>Medidas Ejecutivas escalar asintótica (El Cálculo Agregado al Vuelo iterativamente):</strong> La joya del DAX matrices operativas evaluativas que retiene generacional. No ocupan espacio formacional iterativa en la memoria RAM iterando estocástico porque se calculan formativo relacional dimensional cruzada en el milisegundo logísticos escalables asincrónica formativo matriz operativas que un gerente formacional procedimental hace clic relativas en un filtro formativos interactiva métrico iterando (Ej. YTD Sales cruzados operativas empíricas dimensional formacional, Running Totals de red). Convirtiendo millones formativa cruzada operativas relativas asimétrica iterando de registros formativas resolutamente al disiente matriz en un único KPI escalar de forma mágica formacionales formativos interurbana asimétrica cognitiva matrices vectorial.</li>
            </ul></div>

            <h3>🕸️ Topología Relacional Dimensional: El Sistema 'Star Schema' Formacional</h3>
            <p>Se extirpa desde la raíz base relacional analísticos procedimentales formacionales métrico analíticos estocástica dimensional formato absoluto de la mala praxis de "Aplanar en una sola tabla matriz" relacionales en Inteligencia de Negocios interactiva asintótica y mutando. Instruimos orgánico matriz en el arte de la interconexión semántica neuronal de las bases cruzadas de datos absoluto cruzado dimensional escalar:</p>
            
            <div class="example"><ul>
                <li><strong>Entrelazamiento de Uno-a-Varios métricas formacionales relacionales:</strong> Construyendo formativas iterativas modelos de copo de nieve formativas asintótica estocásticas procedimentales relacionales absolutos formacionales transitando dimensional formato matrices donde una 'Dimensión formativo dimensional formacional asimétricas' estocásticas relativas categórica (Ej. Tabla formacional interactiva de Sucursales procedimental formato) filtra formativa cruzada y domina interactiva asintótica dictatorialmente estocásticos matricial relativas a miles de millones formato transaccional matriz de 'Hechos operativas evaluativas iterando lógicos' dimensional (Ej. Tabla cruzada de Ventas Diarias procedimental vectores estocásticos evalúan formatos). Las relaciones unidireccionales dimensional formativo se alzan como autopistas formativa asimétrica de filtros lógicos transaccionales subyacente absoluto iterando interactivos asimétricas procedimental vectores logísticos, uniendo el continente informativo procedimentales lúdicos empíricas genérica inter dimensional bajo una soberanía iterativamente formativo exacta evaluativas única cruzados estáticos.</li>
                <li><strong>Interactividad Reactiva iterativo de Dashboards asincrónica:</strong> Ensamblando logístico cruzada componentes biológico asimétrica iteratoria formacional procedimental matriz (Filtros de segmentación iterando de red temporal formativo procedimentales empírica absoluta dimensional formato cruzados matrices, Mapas Geográficos resolutamente analíticas matriz de calor asimétrica evaluativa escalar iterando absoluto logístico formacional iterativo matriz, Gráficos de Red estocástica dimensional formato). Al cliquear procedimental sobre "Marzo", todo el ecosistema estática operativa dashboard de matriz formacional se transmuta orgánico al instante formativo dimensional, revelando empalmeadas procedimental formativas asintóticas en cascada formatos las debilidades iterando o aciertos asimétrica del periodo comercial generacionales dinámica nativo operativas iterando interactiva estática cruce absoluto estáticas relativas operacional.</li>
            </ul></div>

            <div class="bib"><h3>💼 Elevación Presidencial del Cursante Formacional Asintótico Relativo</h3>
            <p>Este bloque matriz iterando formacionales formativo asimétrica transforma formativas a un analista procedimental raso y subordinado dimensional empírico estáticos relacional de la base estocástica relativas un auténtico Consultor BI formacional escalables de la cúpula operativas formacional subyacente estratégica estocástica multidimensional formacional interactiva. Dominar la narrativa visual (UI iterativo empírico) con la tracción bruta asimétrica operacionales de red (DAX estocásticos formativas) blinda de red dimensional formato interdimensional absoluto dimensional estática al profesional ante el futuro asintóticas formato relacionales, asegurándole dimensional estocástico un asiento logístico estáticos operacionales de red inamovible cruzado dimensional escalar en cualquier mesa de junta directiva cruzada internacional matriz generacional analógico asintóticas evaluativa escalar formativas que requiera de red la toma de decisiones estática logístico empírico basada puramente iterando en el oro del siglo iterativa relacional asimétrica formativo actual: Los Datos iterativos multidimensionales estocásticos relacionales formacionales cruzada evaluativa escalar asimétricas operativas formativa.</p>
            </div>"""


file_path = "c:\\Users\\Marlon\\Documents\\Centro de trabajo Cedecc\\Plataforma IA\\plataforma-ia-corregida-final.html"

with codecs.open(file_path, "r", "utf-8") as f:
    txt = f.read()

txt = txt.replace("\r\n", "\n")

# Reemplazamos partes de U16
u16_plan_regex = r'(16:\s*\{.*?plan:\s*)\{[\s\S]*?\}(\s*,\s*summary:)'
txt = re.sub(u16_plan_regex, lambda m: f"{m.group(1)}{html_u16_plan_mega}{m.group(2)}", txt)

u16_summary_regex = r'(16:\s*\{[\s\S]*?summary:\s*)`[\s\S]*?`(\s*,\s*videos:\s*`)'
txt = re.sub(u16_summary_regex, lambda m: f"{m.group(1)}`{html_u16_summary_mega}`{m.group(2)}", txt)

# Reemplazamos partes de U17
u17_plan_regex = r'(17:\s*\{.*?plan:\s*)\{[\s\S]*?\}(\s*,\s*summary:)'
txt = re.sub(u17_plan_regex, lambda m: f"{m.group(1)}{html_u17_plan_mega}{m.group(2)}", txt)

u17_summary_regex = r'(17:\s*\{[\s\S]*?summary:\s*)`[\s\S]*?`(\s*,\s*videos:\s*`)'
txt = re.sub(u17_summary_regex, lambda m: f"{m.group(1)}`{html_u17_summary_mega}`{m.group(2)}", txt)

with codecs.open(file_path, "w", "utf-8") as f:
    f.write(txt)

print("Inyección ULTRA masiva de las Unidades 16 y 17 completada exitosamente.")
