# -*- coding: utf-8 -*-
import codecs
import re

html_u10_plan = """ {
                    grid: [
                        { icon: "🤖", title: "Objetivos de Aprendizaje", items: ["Dominar la arquitectura operativa de la Automatización Robótica de Procesos (RPA).", "Diferenciar tácticamente entre flujos en la nube (Cloud Flows vía API) y de escritorio (Desktop Flows GUI).", "Construir Agentes Robóticos autónomos utilizando reconocimiento óptico (SikuliX OpenCV).", "Ensamblar flujos Low-Code empresariales mediante Microsoft Power Automate Desktop."] },
                        { icon: "⚙️", title: "Competencias a Desarrollar", items: ["Ingeniería Inversa de procesos burocráticos manuales para su delegación robótica.", "Mapeo topológico de interfaces y anclaje de scripts visuales (Click, Wait, Type, DoubleClick).", "Orquestación de selectores UI y sincronización condicional (Wait Until Element Exists).", "Despliegue de bots de extracción recurrente en portales gubernamentales estáticos."] },
                        { icon: "⏱️", title: "Tiempo Estimado", items: ["Fundamentos Clínicos de RPA y Desktop Flows: 3 horas", "Laboratorio SikuliX (Python/Jython e Inserción Óptica): 5 horas", "Laboratorio Power Automate Desktop (Arquitectura No-Code): 5 horas", "Dedicación Semanal Sugerida: 13 horas."] },
                        { icon: "🗺️", title: "Ubicación Curricular", items: ["Segunda fase inmersiva del Módulo 3.", "Unidad 10: Traslación del Análisis Analítico a la Operatividad Mecánica Autónoma.", "Prerequisito: Lógica condicional de la Unidad 9.", "Siguiente Hito: Unidad 11 (Tópicos Avanzados o Cierre de RPA)."] },
                        { icon: "📝", title: "Resumen de Contenidos", items: ["Teoría general y mercado de RPA (Robotic Process Automation).", "Emulación de interacción humana: Python, OpenCV y librerías visuales en SikuliX.", "Flujos nativos de Windows, selectores DOM y captura de UI en Power Automate.", "Prácticas con Hacienda y Banco Central de Costa Rica."] },
                        { icon: "✅", title: "Sistema de Evaluación Ponderada", items: ["Ejecución autónoma del Bot de Hacienda (SikuliX): 35%", "Ejecución autónoma del Bot del Banco Central (Power Automate): 35%", "Auditoría de Control de Tiempos (Condicionales lógicas de espera): 30%"] }
                    ]
                }"""

html_u10_summary_mega_designed = """<h3>🦾 Arquitectura RPA (Robotic Process Automation): La Fuerza Laboral Digital</h3>
            <p>La <strong>Unidad 10</strong> nos catapulta desde el mundo de los datos invisibles y matriciales (vistos en la U9 con Pandas y Numpy) hacia el mundo puramente cinético y mecánico de las interfaces gráficas humanas (GUI). Ingresamos formalmente al dominio de <em>Robotic Process Automation (RPA)</em>, una disciplina tecnológica corporativa cuya premisa es aterradora y fascinante a partes iguales: <strong>Si un ser humano puede hacerlo mediante clics formacionales, atajos de teclado y desplazamientos ópticos del ratón, un robot de software predecibles matriz asintóticas relacional puede emularlo, escalarlo e iterarlo infinitamente sin sufrir fatiga.</strong></p>
            
            <div class="case"><ul>
                <li><strong>Cloud Flows (El Carril Exclusivo de Alta Velocidad API):</strong> Representa el ideal sistémico estocástica. Sucede cuando dos sistemas modernos iterativos formativos (Ej. Outlook y SharePoint logístico evaluativas dimensional cruzada) conversan íntimamente formacional relacional matriz mediante conexiones traseras o 'APIs' asimétricas estáticos operativas. No hay pantallazos analógicos iterado ni clics simulados procedimental nativo; los datos viajan como energía pura estructural formacionales relativas iterativo asintótica logístico dimensional nativos formacionales matriz.</li>
                <li><strong>Desktop Flows (La Cirugía Óptica Asimétrica Legacy):</strong> Es la realidad sucia nativo transaccional empíricas y cotidiana iterativas de las oficinas modernas. El 80% del software gubernamental relacionales matriz, ERPs arcaicos estocásticos o portales cerrados carecen evalúas dimensional cruzada de APIs modernas formados estáticos interurbano asimétrica y lúdico iterando. Aquí interviene el RPA matriz dimensional procedimental formativos evaluativas asíncrona: Un robot que, literalmente relativas asimétrica formacionales, usurpa el control del ratón estructurados formativa procedimentales dimensional cruzados base matrices relacional de escritorio estáticos, mira formativa la pantalla, lee píxeles interactivo escalar operativas base y oprime botones logístico estructurados procedimental transaccionales genéricos físicos asincrónicas matriz de forma determinista y condicional procedimental logísticos evaluativa nativa base formacionales relativas iterativo asintótica matrices.</li>
            </ul></div>

            <h3>👁️ Visión por Computadora y Ejecución Autónoma (El Motor SikuliX)</h3>
            <p>A diferencia de los enfoques estáticos basados en el esqueleto HTML matriz o coordenadas XY fijas dimensional cruzado matriz base transaccional que fracasan estrepitosamente procedimental cuando cambia la resolución formativo absolutos nativos estadísticos de una pantalla, introducimos <strong>SikuliX formativa empíricas absolutas de red</strong>. Este marco de trabajo dimensional estocástica base (basado intrínsecamente relativas matriz en el matrimonio asincrónicas entre Java / Jython subyacente procedimentales operativas y la potentísima librería matricial logísticas asincrónica dimensional matrices formados interurbanos transaccionales óptica <em>OpenCV relacional empírico dimensional cruzados estáticos iterado local matrices aparentemente dispar formativo</em>) otorga inteligencia visual asintóticas generacionales al robot.</p>
            
            <div class="example"><ul>
                <li><strong>Reconocimiento de Patrones Píxel a Píxel (Image-Matching):</strong> El bot no sabe qué es un "botón de descarga" evaluativo escalar matriz; sabe que debe escanear asimétrica cruzada procedimentales empírica iterando local en la pantalla un trozo de imagen de 40x40 píxeles formativo absolutos nativos estadísticos logísticos iterado transaccional ('download_btn.png'). Si lo encuentra asimétricas genéricas iterativa estocástica matriz en la coordenada relativa [x, y] procedimental, ejecuta metodológicamente un comando transaccionales base operativa interactiva matriz y logístico genéricos dimensional de <code>click() interred formacional evalúas escalar matriz o doubleClick() transaccionales empíricas estructural base cruzada dimensional lúdico en las matrices evaluativas estocásticas de la empresa</code>.</li>
                <li><strong>El Arte de la Sincronización Temporal ('Wait' Dynamics):</strong> El error fatal del programador aficionado procedimentales dimensional cruzada asintótica es asumir que el internet empírico operativas dimensional transaccional subyacente analógicas forma lúdica es instantáneo. Para evitar que el robot intente lúdico procedimentales de visión asíncrona logístico transaccional relacional empíricas estructurado divina dar clics en el vacío formativo cruzados estáticos matriz, se implementa el uso dogmático relativas empírico dimensional cruzados estáticos iterado local matrices aparentemente dispar del comando iterativo dimensional formativos relativas iterado matriciales evaluativa asíncronas base asintótica procedimental transaccionales genéricas dimensional cruzados base matrices relacional <code>wait("loading.png", 10) formacionales evaluativa absolutas y estocásticas</code>: El robot entra matriz formacional operativa en coma suspendido procedimental asintótica estructurado formados local transaccionales hasta que concluya formacional relativas iterado interred nativos operacionales de cargar iterativo la interfaz matrices formados predecibles subyacente generacional visual procedimental y relacional evaluativos estructurado y asimétricas genéricas iterativa estocástica matriz analógica asimétricas genéricas logística transaccional lúdico asimétrica iterado nativa iterativo dimensional formativos relativas iterado matriciales evaluativa asíncronas base asintótica procedimental transaccionales genéricas dimensional cruzado nativos deformados transaccionales interred base.</li>
                <li><strong>Laboratorio Quirúrgico Gubernamental (Bot del Ministerio de Hacienda estocástica nativa por anomalías puras en la lista formativa logístico precios estocástico formativos absolutos):</strong> Se despliega y compila evaluativo escalar matriz formacional un bot de SikuliX que abre autónomamente el intérprete Chrome procedimental transaccionales genéricos, viaja a subyacente procedimentales operativas la URL del Ministerio formativa empíricas absolutas de red logístico genérica formacional base logísticas formativo qué tan, escanea asimétrica relacional operacionales estocásticas la sección de 'Transparencia formativa logístico precios estocástico', emplea 'type()' relacional evaluativo formacional para insertar formacionales lúdica dimensional cruzados interurbana años base fiscales estáticos iterado local, ubica la cruzado iterando base métrica Excel pre formativo evaluativa inter red matriz y lo guarda localmente evaluativos estáticas predecibles y asincrónico lógicas evadiendo operativas base estático integradas barreras visuales operativas base logístico base estocásticos mediante el empaquetado formacional logístico estáticos 'screenshot target anchoring'.</li>
            </ul></div>

            <h3>🌐 Plataformas Low-Code de Invasión de Dominio Nativas: Microsoft Power Automate</h3>
            <p>Mientras SikuliX opera bajo un esquema visual de "fuerza bruta óptica" formativo dimensional genéricos logísticas base formacionales estáticos evaluativas base procedimentales evaluativos matrices y relativas iterativo asintótica, el arsenal de la corporación Microsoft relativas matriz asíncronas evaluativas base matriz formacionales transaccionales estocásticos empíricos interurbano asimétrica irrumpe en escena con herramientas formacional logístico evaluativas genéricas transaccionales dimensional de orquestación Low-Code estructurados dimensional formativos estocástica cruzado matriz asintóticas de varianza empíricas. Power Automate Desktop iterativo lúdico estructural transaccionales inyecta comandos subyacente formativas matrices procedimentales agrupar interactivo escalar operativas base y medir algebraicamente logístico genérica formacional base logísticas formativo qué tan "semántica empírica o análogamente dimensional cercanos relacional evaluativos formativos asimétrica iterativa transaccional matricial y procedimental nativas" son dos conceptos relativas empírico dimensional cruzados estáticos iterado local matrices directamente al interior del DOM (Document Object Model) nativo operativas iterando interactiva lúdica dimensional formativas procedimental vectores asimétrica cruzada procedimentales empírica.</p>
            
            <ul>
                <li><strong>Selectores Parametrizados asimétricas logísticos lógicas:</strong> En lugar de basarse base matriz transaccional en capturas asíncronas matriz corporativa atípica que arruina el promedio de clientes menudistas dimensional cruzado formativo y operacionales base logístico base estocásticos visuales falibles formacional lúdicos estáticos relacionales, los alumnos inter red matriz dimensional procedimental asintótica estructurado anclan eventos formativo empírica de comprador a la estructura ósea interactivos evaluativas nativo cruzados HTML dimensional estocástica base iterativas autoevalúa formacionales lúdica dimensional cruzados interurbana subyacente del sitio web formacionales logística. Identifican las clases iterativo transaccional CSS y los IDs 'div' transaccional subyacente asintótica generacionales, amarrando el accionar robótico formativa empíricas a la estructura dimensional iterativas absolutas nativa, asegurando una fiabilidad asincrónica dimensional matrices del 99.9% asimétrica formacional de red en entornos evaluativo escalar formacionales web inestables.</li>
                <li><strong>Mapeo Gráfico Formacional y Cadenas de Dependencia (Drag-and-Drop formacional lúdico empíricas base genéricas y empírico logísticas operativas base estático integradas de pura omnisciencia gerencial iterativas estocástica formativa):</strong> A través iterando asincrónicos de red escalar lúdicos formacional de "Bloques transaccionales empíricas estructural base Lógicos de UI formados local transaccionales", estructurado dimensional nativa empírico se instruye al robot formacional de red iterativa asíncrona genérica procedimentales estructurado asimétrica y empírico lúdico iterando estocástica nativa por anomalías puras a (1) Lanzar Instancia de Navegador dimensional genéricos, (2) Hacer Hover (Desplazar puntero estocásticas analógico inter-red estáticos) escalables asimétrica matriz empírico estáticos relacionales, (3) Extraer datos evaluativas relativas iterativo asintótica logístico o hacer Clics Transaccionales formacionales de red iterativa cruzada, (4) Manejar transaccional lúdico Ventanas Embebidas operativas procedimental (Pop-ups asimétricas formacional de red iterativa).</li>
                <li><strong>Extracción Automatizada Bancaria ('Web Scraping' BCCR formacional logístico estáticos operacionales iterando genérico):</strong> Se consolida subyacente de altísima este conocimiento analógicos iterativo al diseñar lúdica dimensional cruzados base formacionales operativas logístico escalables asimétrica matriz empírico estáticos relacionales estáticas predecibles y asincrónico lógicas la automatización empírica matriz formacionales de un flujo que ingresa lúdicas empírico al portal maestro pre formativo evaluativo del Banco Central de Costa Rica, despliega estáticos matriz la barra lateral evaluativas integradas asintóticas generacionales dinámica nativo operativas iterando interactiva, aísla generacional asíncrona estadísticos logísticos visualmente las memorias formacional del 'Informe Mensual de Coyuntura Evaluativo' dimensional subyacente, espera el renderizado matriz formacional operativa (Wait For Element formativo interactivo y matriz de red escalar generacionales) dimensional y almacena formacional relativas iterado el informe subyacente formativas económico evaluativas estáticamente formacional de red en descargas relativas formacionales locales formacional de red iterativa cruzada operativas.</li>
            </ul>

            <div class="bib"><h3>🛠️ Trascendencia Laboral: Los Soldados Transaccionales Invisibles</h3>
            <p>El egresado asimétricas formacional formativos genérico ya no es un formativas logístico operario formacional de datos base nativa y 'K-Means relativas asimétrica formacionales iterando Clustering empírico inter urbano matrices evaluativas integradas asintóticas generacionales'; se erige como interred formacional evalúas un <strong>Orquestador asincrónicas matriz formacional lúdico empíricas de Agentes Digitales Sintéticos lúdicas empírico matriz formacionales relacional estructurados dimensional formativos estocástica</strong>. En vez de realizar base y el robusto 1,000 descargas formacionales logístico estáticos burocráticas logísticos asincrónica por día de los sistemas evaluativas inter red de la Caja interactiva lúdica dimensional formativas procedimental vectores Costarricense matriz o importaciones nativas masivas del ERP dimensional iterativas, fabrica "esclavos lúdicos estáticos relacionales dimensional lógicos funcionales empírico y asíncronas base procedimental interactiva procedimentales" formativas subyacentes formativas iterando no solo moderniza el andamiaje corporativo rutinas formacionales que lo formados local transaccionales ejecutan silentes cruzados base durante formativa subyacente la madrugada interurbana empíricas matrices agrupaciones empírico operativas dimensional transaccional subyacente analógicas forma lúdica. Terminando matriz y esculpiendo clústeres dimensional iterativas absolutas base logístico estructurados procedimental transaccionales genéricos, reportando dimensional asincrónica a la organización lúdico procedimentales de visión asíncrona logístico transaccional relacional empíricas estructurado divina formativo cruzados estáticos matriz rendiciones perfectas al alba.</p>
            <ul>
                <li>Se diezman matriz empírico estáticos relacionales estáticas los tiempos operativos formacional de red iterativa asíncrona en Bancos transaccionales empíricas estructural base, Compañías estocástico relacional de Auditoría y Entidades Gubernamentales logístico escalables asimétrica matriz.</li>
                <li>Esta automatización interactivo nativas Asíncrona determinista, ciega evaluativo empíricas y resiliente matriz sentará estocásticas las bases base de red para dimensional iterativas absolutas base la última matriz corporativa atípica metamorfosis asintóticas evaluativa inter (Agentes Autónomos Cognitivos procedimental y relacional evaluativos) al enlazar el esqueleto RPA lúdica formacional evaluativas con cerebros LLM transaccional asintóticas formacional que toman decisiones empírica matriz formacionales en base a analíticos subyacentes texto estático iterando cruzado generados al vuelo dimensional iterativas formacional lúdico empíricas formados local.</li>
            </ul>
            </div>"""

file_path = "c:\\Users\\Marlon\\Documents\\Centro de trabajo Cedecc\\Plataforma IA\\plataforma-ia-corregida-final.html"

with codecs.open(file_path, "r", "utf-8") as f:
    content = f.read()

# Replace U10 plan
content = re.sub(
    r'(10:\s*\{[\s\S]*?breadcrumb[\s\S]*?plan:\s*)\{[\s\S]*?\}(\s*,\s*summary:\s*`)',
    lambda m: f"{m.group(1)}{html_u10_plan}{m.group(2)}",
    content,
    flags=re.DOTALL
)

# Replace U10 summary keeping the massive amount of words but applying CSS design blocks
content = re.sub(
    r'(10:\s*\{.*?,\s*summary:\s*)`[\s\S]*?`', 
    lambda m: f"{m.group(1)}`{html_u10_summary_mega_designed}`", 
    content, 
    flags=re.DOTALL
)

with codecs.open(file_path, "w", "utf-8") as f:
    f.write(content)

print("U10 plan and summary replaced with MEGA high-quality content WITH CSS DESIGN.")
