# -*- coding: utf-8 -*-
import codecs
import re

html_u6_summary = """<h3>🌍 La Era del Agentic AI y el Protocolo MCP (2024-2025)</h3>
            <p>El desarrollo de la Inteligencia Artificial ha dado un salto cuántico. Antes de 2024, la inteligencia artificial se encontraba aislada dentro de las interfaces de chat convencionales. Los modelos fundacionales (LLMs) podían entregar respuestas maravillosas basadas en texto, sugerir correcciones y redactar ensayos, pero eran incapaces de interactuar con el mundo real. No podían observar tus archivos confidenciales en la nube, manejar tu calendario de reuniones, ni alterar bases de datos corporativas sin requerir la construcción de APIs personalizadas, lo cual requería meses de desarrollo experto y un presupuesto astronómico.</p>
            <p>Todo esto cambió radicalmente con la creación del <strong>MCP (Model Context Protocol)</strong>. Desarrollado y lanzado originalmente por Anthropic (los creadores de la familia de modelos Claude) a finales de 2024, el MCP se posiciona indudablemente como el "USB-C de la Inteligencia Artificial". Consiste en un estándar universal de código abierto capaz de conectar poderosos modelos de lenguaje con los sistemas corporativos reales y herramientas de trabajo del día a día.</p>
            
            <div class="example"><h4>🔄 Beneficios Fundamentales del Protocolo MCP:</h4>
            <ul>
                <li><strong>Erradica el Vendor Lock-In:</strong> Elimina la dependencia esclavizante hacia proveedores únicos. Antes, si cambiabas de Microsoft a Google, perdías todas tus integraciones IA. Hoy, el protocolo universal enruta las solicitudes bidireccionalmente sin importar el proveedor.</li>
                <li><strong>Comunicación Cliente-Servidor Estructurada:</strong> Implementa una estructura robusta basada en JSON Manifest. El 'Cliente' (el chat o la IA) se comunica con el 'Servidor' (nuestra base de datos o aplicación) usando parámetros inmutables y predecibles, evitando errores de lectura y caídas de sistema.</li>
                <li><strong>Autonomía Pragmática:</strong> Posibilita a los agentes inspeccionar, asimilar y ejecutar comandos sobre servicios de terceros en tiempo real sin reformatear la infraestructura de IT.</li>
            </ul></div>
            
            <h3>💡 Integraciones MCP Activas en la Práctica Empresarial</h3>
            <p>El protocolo MCP ya no es una teoría; ha sido rápida y extensamente adoptado de manera nativa por la rama de automatizadores globales (como n8n y Make) e IDEs modernos en toda la industria Q2 2025. Veamos cómo operan las tres grandes potencias de la IA Generativa al día de hoy:</p>
            
            <div class="case">
                <p><strong>1. En el Ecosistema Gemini (Workspace):</strong> Mediante las integraciones activas interconectadas de Workspace, es factible indicarle a la red neuronal de Gemini que analice correos entrantes, estructure la data, y cree eventos masivos en el Google Calendar o indague en tu bandeja de entrada unificando flujos e interlocutores. Sin embargo, su conexión actual en fase inicial con Gmail posee todavía inestabilidades de filtrado de datos respecto a otras herramientas más maduras, descartando en ocasiones asuntos prioritarios sin justificación.</p>
                <p><strong>2. En el Ecosistema ChatGPT (OpenAI):</strong> El protocolo MCP nativo que ostenta OpenAI autoriza el despliegue de puentes instantáneos conectando repositorios densos como Dropbox, Microsoft Teams o Google Drive directamente al asistente. Esto permite que el motor GPT-4 indexe directorios densos, lea docenas de PDFs de "Econometría Empresarial" y extraiga métricas interrelacionadas o genere resúmenes ejecutivos sin que el usuario deba descargar previamente un solo archivo a su disco duro local.</p>
                <p><strong>3. En el Ecosistema Claude (Anthropic):</strong> Por haber fundado el protocolo de manera nativa, Claude AI ofrece un repertorio abrumadoramente grande de conexiones. Su mayor exponente es la capacidad de usar conectores "Desktop" de escritorio locales, que le otorgan permisos para manipular archivos físicos directamente dentro de arquitecturas Windows o Mac, editar e inyectar código, y leer carpetas privadas ancladas en el disco duro al instante sin requerir subidas previas a la nube.</p>
            </div>

            <h3>🤖 Evolución Brutal: De Chatbots a Agentes Especializados al Rescate</h3>
            <p>Con el MCP funcionando activamente como la vía neurológica o "médula espinal" de la Inteligencia Artificial, a mediados del 2025 explotaron comercialmente los denominados "Agentes de IA" (Agentic Entities). Diferenciándose abismal y brutalmente del clásico "Chatbot de propósito general" con el que interactuábamos en 2022 o 2023, estos Agentes Superiores tienen misiones analíticas, control de red interconectado y asombrosas capacidades de interacción resolutiva ininterrumpida sin detenerse por confirmación en cada micropaso. Representan el salto real desde un contestador automático inteligente hacia un verdadero sistema o empleado autónomo a escala técnica.</p>
            
            <div class="example"><h4>⚡ Plataformas Agénticas del Mercado Actual (Estado del Arte Q2 2025)</h4>
            <ul>
                <li><strong>Kimi 2.5 (El Analista Documental):</strong> Kimi es un agente soberbio y altamente focalizado en la creación documental extensa e ingestión de datos asimétricos. Puede ingerir un PDF empresarial técnico denso de cientos de páginas, transmutarse a su rol configurado (ej. 'Analista Adaptativo o Visual Académico'), y escupir sin sudar un Slide Deck profesional (Presentación) de 30 a 50 páginas altamente pulido, esquematizado formalmente y estructurado, aniquilando los cortos límites de tokens habituales observados en plataformas de generación pre-agénticas como Gamma, demostrando su increíble ventana y retentiva de contexto operativo.</li>
                <li><strong>Genspark (El Asistente Operativo Asíncrono):</strong> Este Agente destaca fenomenalmente en la trazabilidad inmensa de tareas logísticas empleando a fondo sus MCPs preconfigurados. Si le inyectas tus correos corporativos, no se limita a narrarte un triste resumen superficial; Genspark explora inteligentemente inmensos y bifurcados hilos anidados, abre él mismo los archivos adjuntos en segundo plano (como profundas proformas de reparación o quejas PDF), correlaciona los datos cruzados, elabora analíticamente la solución, prepara el borrador del email y, lo más asombroso, realiza el envío final (disparador SMTP de red) de manera autónoma completamente por ti si se lo autorizas activamente.</li>
                <li><strong>Manus AI (El Entorno Frontend Desplegable):</strong> Manus se consolida como un ecosistema brutal sin precedentes para aquellos perfiles que buscan transformar "Prompts" literarios directos en interfaces Web reales ('Zero-shot App Generation'). Se le puede solicitar, a modo de ejemplo conversacional, desarrollar integralmente un evaluador estadístico de riesgos para la bolsa de valores; la IA no solo contestará de forma textual inerte, sino que codificará la lógica, generará el React correspondiente y renderizará en vivo de inmediato una <em>Web App Simuladora Gráfica</em> manejable ante tus ojos. Ésta estará dotada de menús deslizantes, filtros paramétricos de perfil de usuario (ej. Conservador/Agresivo) y proyección de retornos matemáticos incrustados dentro del propio chat de respuesta.</li>
                <li><strong>Minimax (El Research Investigador):</strong> Denominado comúnmente como un Agente de Research avanzado y algorítmico. Excepcional explorador y programador analítico matemático: se sumerge intrépidamente en los grandes repositorios de internet o bases subidas y, lo que le otorga su fama colosal, puede escribir él solo rutinas de programación en lenguaje Python puras en su sandbox aislado en la nube (visibles en las pestañas exclusivas de /Files y /Code de su propio front). Ejecuta estos códigos matemáticos para iterar sin parar, autogenerándote gráficas demográficas complejas renderizadas y reportes hiper estructurados con base en datasets estáticos o csv financieros subidos, logrando análisis muy superiores a ChatGPT Data Analyst sin fallas en memorización o variables.</li>
            </ul></div>
            
            <div class="bib"><h3>🛡️ Retos Corporativos en la Adopción a Gran Escala</h3>
            <p>La adopción febril y actual de los ecosistemas de agentes cibernéticos con MCP acarrea tres macrodesafíos ineludibles para los líderes de desarrollo, las oficinas de privacidad y los arquitectos de sistemas en la modernidad corporativa:</p>
            <ol>
                <li><strong>Seguridad de Datos y Riesgo PII (Personally Identifiable Information):</strong> Es un mandato inquebrantable aprender a limitar estrictamente hasta dónde posee autorización, injerencia o permiso el agente sobre las macro bases de nuestro CRM transaccional. Dejar libre el espectro puede generar fugas masivas catastróficas.</li>
                <li><strong>Trazabilidad Funcional y Supervisión (Human-In-The-Loop):</strong> ¿Quién recae como el responsable penal o moral si un poderoso Agente Asíncrono de Genspark envía y efectua un presupuesto financiero fatal, irreversible y estadísticamente erróneo a las bases de un cliente importante corporativo? Es legal y estrictamente obligatorio en 2025 incorporar pasos preprogramados metódicos de "Review in-the-loop" (Revisión humana obligatoria paralizante) que obliguen a cortar sistemáticamente a la orden los ciclos automáticos productivos en tareas críticas de alta responsabilidad comercial y legal.</li>
                <li><strong>Control de API y Costos Sistémicos Multiplicativos (M/N):</strong> Otro desastre evitable es controlar el 'Bucle de Generación Infinito', es imperativo programar limitaciones y cotas temporales para salvaguardar el erario en caso extremo fortuito de que la IA autónoma sufra una profunda y sistémica alucinación multi-tarea (hallucination loop) donde empiece a cruzar llamadas de facturación recursiva API gastando crédito de manera indiscriminada segundo a segundo sin que logremos darnos cuenta previo colapso monetario informático.</li>
            </ol>
            </div>"""

html_u6_plan = """{
                    grid: [
                        { icon: "🎯", title: "Objetivos Estructurales de Aprendizaje", items: ["Comprender exhaustivamente la colosal evolución desde los chatbots conversacionales estáticos pasivos hacia ecosistemas de agentes autónomos ejecutores (Agentic Paradigms) interurbanos interactivos reales.", "Dominar orgánicamente el concepto matricial de MCP (Model Context Protocol) fundado por Anthropic, así como su arquitectura técnica subyacente básica como el USB de la IA.", "Implementar de manera segura y controlada diversas integraciones MCP corporativas reales en plataformas analíticas de peso global masivas como Gemini, ChatGPT Data y las redes Claude AI.", "Operar y supervisar eficientemente sistemas de plataformas agénticas altamente especializadas asíncronas de primer mundo (Kimi 2.5, Genspark Mail, Manus Frontend, Minimax Analytics).", "Diseñar, guiar y supervisar aplicaciones interactivas iterativas simuladas web, flujos documentales académicos densos y automatizaciones de envíos masivos de correo delegando de forma verificable en eficaces Agentes de Inteligencia Artificial."] },
                        { icon: "💡", title: "Competencias Críticas a Desarrollar", items: ["Implementación segura nativa verificada y control analítico restrictivo local de conexiones vitales en Workspace corporativo Microsoft y nubes integradas de disco blando usando infraestructura MCP nativa preinstalada e interfaces de servidor.", "Planificación, segmentación y orquestación magistral directiva de tareas logísticas asíncronas complejas desarrolladas en la Web: desde la ingesta interurbana y procedimental local de adjuntos largos anidados complejos en múltiples canales cruzados, hasta llegar exitosamente hacia la generación concluyente documentada oficial de reportes cruzados financieros, analítica deductiva descriptiva predecible estadística y aplicaciones modulares web interactivas renderizadas visualizadas gráficamente en vivo de manera predecible algorítmica y asimétrica de la industria corporativa actual sin latencia limitadora ni códigos dependientes externos que ralenticen el proyecto.", "Evaluación profundamente crítica del infame problema de interconexión y esclavización matriz informático del mercado analizado denominado como el 'Vendor Lock-in' restrictivo privativo temporal logrando así internalizar de tajo en consecuencia la necesaria iterativa imperiosa y febril adopción a nivel continental o internacional estricta formal y temporalmente verificada sistémica en tiempo real iterativo predeterminado interactiva satelital asíncrona validada de estándares y protocolos estables iterativos abiertos y no dependientes base operacionales modulares analíticos asimétricos validados estructurales.", "Gestión profesional, restrictiva y control perentorio iterativo riguroso y humano asimétrico formal operativo restrictivo legal operativo de riesgos operacionales estructurales documentales operacionales empresariales, atajando, combatiendo y anulando orgánicamente limitadamente las gravosas alucinaciones sistémicas interurbanas pre operacionales asíncronas temporales base en los variados agentes procedimentales productivos de escalamiento masificado hiper iterativos exóticos y altamente autónomos de alta concurrencia de mercado."] },
                        { icon: "⏱️", title: "Distribución Modular del Tiempo en Agenda", items: ["Cronograma Analítico de la Semana 6 exhaustiva totalitaria general operativa del programa", "Sesiones sincrónicas magistrales en Labs estructurados técnicos locales: 12 impactantes horas de duración interactiva", "Trabajo y lecturas asincrónicas documentales procedimentales requeridas iterativas subyacentes operativas de manuales pre operativos: 3 intensas valiosas horas base relacional iterado pre configurado", "Diligencia práctica sumatoria recomendatoria complementaria analítica extra obligatoria e intensiva en Labs locales MCP de conectividad corporativa matriz central interurbana: 5 rigurosas horas estocásticas extras de iteración asíncrona", "Dedicación temporal acumulada y estimada volumétrica total semanal predimensionada asimétrica proyectada de control base y métricas formales base esperada totalitaria general sumada y proyectada de iteración libre controlada estimada base: 20 abrumadoras y densas productivas exigentes potentes formales estructuradas profundas masivas y abocadas y valiosas horas de impacto."] },
                        { icon: "📚", title: "Ubicación Curricular en el Programa", items: ["El presente módulo transversal se encuadra holística estructurada analíticamente asíncrona relacional interconectada al Módulo 2 Operacional general: Herramientas IA para Automatidad Base Relacionada Inteligente de la Industria local", "Correspondiente sin atenuantes en calendario secuencial a la abarcativa indispensable e ineludible poderosa base constitutiva analítica fundamental y estricta Unidad número 6 global (Constituyendo formalmente y de plano la 6 de las 7 potentes módulos de una Extensión matriz técnica procedimental inmersivamente avanzada) contenida en este poderoso iterativo formal y estructurado de avance formativo escalar base módulo general interactivo asíncrono temporal base satelital corporativo.", "Prerequisito indispensable procedimental estricto interconectado temporal formativo necesario obligatoriamente secuenciado previamente evaluado operativo normado restrictivo y calificador de métricas base logradas previamente requeridas asíncronamente: Vencimiento de iterativas prácticas analíticas formales teóricas Unidad base operativa 5 (Automatización Generativa y Algoritmos predecibles de chat pasivo base formativo escalar).", "Desarrollo inminente formativo transitorio y conectivo posterior estricto inmediato base estructural operativo pre normado normativo: La abarcativa, imperativa e insondable Unidad masificada base teórica analítica perentoria conectiva número 7 operativa experimental libre denominada como de inmersión total en Google AI Studio experimentación Multimodal Avanzada predecible base y Arquitectura Agent-First IDE pre operacional asimétrica nativa general estructurada escalable operativamente interurbana estructurada de alto octanaje relacional satelital procedimental."] },
                        { icon: "📝", title: "Resumen Exhaustivo de Contenidos", items: ["Historia Cronológica Analítica Estructurada Automática Temporal: Transición macro sistémica del ecosistema pasivo chat de LLMs hacia el robusto macro ecosistema integrado del estándar matriz universal conector inter redes y conector físico MCP de adopción global interurbano predefinido Q2 2025 relacional analítico asimétrico de mercado estandarizado iterativo.", "Arquitectura y bases técnicas subyacentes analíticas de red física pre formadas restrictivas puras formales del sistema de intercambio de hipertexto iterativo asíncrono temporal MCP y JSON-RPC relacional temporal base iterativo pre formado analítico operativo base: La interacción y fundamentación matriz constituyente interactivo relacional en los sistemas dinámicos cliente/servidor base con JSON formados preestablecidamente iterativos estructurados analíticos formales temporales.", "Plataformas y Cúmulos interactivos modulares pre organizados inter red locales base 1 asimétricas base analíticas y operacionales: Kimi 2.5 relacional configurativo y analítico orientado masivamente iterativo pre estructural satelital corporativo transaccional interactivo en desarrollo generativo documental local extenso para ofimática académica descriptiva.", "Ecosistemas Agénticos de investigación cruzada inter redes formales base analítica 2 estocásticas operacionales modulares asíncronas temporales formadas operacionales asíncronas temporales estandarizados nativamente: El poderío omnisciente iterativo resolutivo procedimental y pre definido estático nativo analítico iterado subyacente de Genspark operativo y transaccional base para lectura extensiva analítica iterativa asimétrica satelital base transversal de redes y bandejas documentadas asíncronas de mail SMTP.", "Arquitectos Sintácticos de Front-End Visual Interactivo y Desarrollo Autónomo Temporal iterativo generativo analítico y formativo local asimétrico pre operacional estandarizado satélite pre configurado de bases 3 asimétrico iterado virtual: La imponente destreza iterativa satelital base procedimental constructora analítica nativa sintáctica temporal y efímera procedimental pre formativa estructurada nativa modular de Manus AI pre programada operativa temporal como simuladora.", "Investigadores Asíncronos formados operativos temporales base analítica asimétrica estocástica estructurada iterativa iterada analítica iterativa estructurada 4 pre operativa inter urbana nativa algorítmica y asíncrona: Minimax asimétrico satelital base analítico estructurado de desarrollo programático nativo temporal base para inmersiones algorítmicas python y reportes financieros automáticos estructurados documentados base de redes interconectadas transversales satelitales analizados transversales iterativos subyacentes asíncronos corporativos analíticos."] },
                        { icon: "✅", title: "Sistema General y Protocolario de Evaluación", items: ["Planificación estricta analítica de rúbrica basada orgánicamente estructural en Configuración procedimental obligatoria base inicial temporal simulada interactiva pre formativa normativa de laboratorio de entorno base local y en nube activo propio MCP con pruebas tangibles operacionales transaccionales nativas base relacionales temporales interactivo estático asimétrico temporal (Documentables estrictamente vía múltiples pantallas o Capturas de logs): Importante asignación operativa formal relacional temporal procedimental normativa restrictiva del 30% del volumen pre formativo general asíncrono escalable iterado.", "Documento formal, operativo perentorio pre formativo procedimental iterativo y descriptivo estricto analítico satelital de revisiones métricas base formadas Pruebas de Software o Aplicativos web iterados asimétricos operados lógicamente vía nativa asíncrona satélite operativamente simulados generados temporalmente operados nativamente estructurales por Manus AI y revisados inter urbanamente de forma relacional asíncrona temporal base asimétrico y evaluados satélite: 30% base.", "Entregable final operativo y estructural formato formal relacional base académico estricto validado interactivo generado temporalmente iterativo como Trabajo base final analítico temporal operativo estricto evaluativo exhaustivo y operativo procedimental nativo desarrollado estructuralmente pre configurado con Kimi 2.5 nativa analítica interactivo satélite: 20% general.", "Encuestas activas formativas sumatorias formativas operacionales de selección y control iterativas simulado base métricas analógicas de retroalimentación de base de conocimientos teóricos y formales inter redes base relacional (Respuestas a componentes evaluativos integrados algorítmicos Quiz y trivias y Simulador cruzadas y redes satelital base formales e integraciones formadas base relacionales restrictivas base inter redes): El porcentual subyacente complementativo orgánico remanente asimétrico formativo 20% formativo y sumario base evaluativo interactivo simulado iterado nativo y operativo formativo."] }
                    ]
                }"""

file_path = "c:\\Users\\Marlon\\Documents\\Centro de trabajo Cedecc\\Plataforma IA\\plataforma-ia-corregida-final.html"

with codecs.open(file_path, "r", "utf-8") as f:
    content = f.read()

# Replace summary and plan using regex
content = re.sub(
    r'(6:\s*\{[\s\S]*?plan:\s*).*?(,\s*summary:).*?`[\s\S]*?`', 
    lambda m: f"{m.group(1)}{html_u6_plan}{m.group(2)} `{html_u6_summary}`", 
    content, 
    flags=re.DOTALL
)

with codecs.open(file_path, "w", "utf-8") as f:
    f.write(content)

print("Unidad 6 summary and plan replaced with MASSIVE chunks.")
